### ISSUE TITLE
bug in mixin that causes server crash

### ISSUE THREAD

**Issue by Monster-Zer0** [Draylar/get-off-my-lawn#30]
this mixin https://github.com/Draylar/get-off-my-lawn/blob/2dcd3c789fc7d1ca2f9adf3434ebf5be31232c21/src/main/java/draylar/goml/mixin/augment/EndermanEntityMixin.java

here is the log

https://hatebin.com/uoyespitiq

not sure what the issue is, but notsteven helped me figure out the issue

**Comment by Draylar** [comment]
I don't see a crash in your hatebin. Is that the full log?

**Comment by Monster-Zer0** [comment]
it's the full log. it just freezes at the end there and everyone is kicked off

**Comment by Monster-Zer0** [comment]
nevemind apparently there is a limit

**Comment by Monster-Zer0** [comment]
i am making my own hastebin real quick then post the full log

**Comment by Monster-Zer0** [comment]
here is the juicy part https://paste.alloffabric.com/ogotosures.csharp

**Comment by Monster-Zer0** [comment]
https://paste.alloffabric.com/ulalejadad.yaml

crash log

**Comment by Draylar** [comment]
Fixed in 1.3.3-beta, which will be out in a second. I assume somebody somehow managed to remove a claim block without removing the claim (like a broken item that bypasses claims and removed the anchor, or an operator using /setblock to remove the anchor). In the next update, any invalid claims like this will self-delete themselves and not NPE. Let me know if you encounter any other issues. Thanks for the report!
